
<!DOCTYPE HTML>
<html lang="" >
    <head>
        <meta charset="UTF-8">
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
        <title>5跨域 · GitBook</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="description" content="">
        <meta name="generator" content="GitBook 3.2.3">
        
        
        
    
    <link rel="stylesheet" href="../../gitbook/style.css">

    
            
                
                <link rel="stylesheet" href="../../gitbook/gitbook-plugin-highlight/website.css">
                
            
                
                <link rel="stylesheet" href="../../gitbook/gitbook-plugin-search/search.css">
                
            
                
                <link rel="stylesheet" href="../../gitbook/gitbook-plugin-fontsettings/website.css">
                
            
        

    

    
        
    
        
    
        
    
        
    
        
    
        
    

        
    
    
    <meta name="HandheldFriendly" content="true"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="../../gitbook/images/apple-touch-icon-precomposed-152.png">
    <link rel="shortcut icon" href="../../gitbook/images/favicon.ico" type="image/x-icon">

    
    <link rel="next" href="6Ajax.md" />
    
    
    <link rel="prev" href="JS-4数据类型转换.html" />
    

    </head>
    <body>
        
<div class="book">
    <div class="book-summary">
        
            
<div id="book-search-input" role="search">
    <input type="text" placeholder="Type to search" />
</div>

            
                <nav role="navigation">
                


<ul class="summary">
    
    

    

    
        
        
    
        <li class="chapter " data-level="1.1" data-path="../../">
            
                <a href="../../">
            
                    
                    Introduction
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.2" data-path="../../readme.html">
            
                <a href="../../readme.html">
            
                    
                    说明
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.3" >
            
                <span>
            
                    
                    HTML
            
                </span>
            

            
            <ul class="articles">
                
    
        <li class="chapter " data-level="1.3.1" data-path="../html/HTML5-特性说明.html">
            
                <a href="../html/HTML5-特性说明.html">
            
                    
                    HTML5-特性说明
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.3.2" data-path="../html/HTML5-input标签介绍.html">
            
                <a href="../html/HTML5-input标签介绍.html">
            
                    
                    input标签介绍
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.3.3" data-path="../html/HTML字符实体.html">
            
                <a href="../html/HTML字符实体.html">
            
                    
                    HTML字符实体
            
                </a>
            

            
        </li>
    

            </ul>
            
        </li>
    
        <li class="chapter " data-level="1.4" >
            
                <span>
            
                    
                    JavaScript
            
                </span>
            

            
            <ul class="articles">
                
    
        <li class="chapter " data-level="1.4.1" data-path="JS-正则表达式.html">
            
                <a href="JS-正则表达式.html">
            
                    
                    正则表达式
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.2" data-path="dom.html">
            
                <a href="dom.html">
            
                    
                    dom
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.3" data-path="JS-排序算法.html">
            
                <a href="JS-排序算法.html">
            
                    
                    排序算法.md
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.4" data-path="JS-正则表达式.html">
            
                <a href="JS-正则表达式.html">
            
                    
                    正则表达式
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.5" data-path="JS-1对象-构造函数-原型链.html">
            
                <a href="JS-1对象-构造函数-原型链.html">
            
                    
                    1对象-构造函数-原型链
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.6" data-path="JS-2node搭建服务器、API接口编写.html">
            
                <a href="JS-2node搭建服务器、API接口编写.html">
            
                    
                    2node搭建服务器、API接口编写
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.7" data-path="JS-3this-call-apply-bind.html">
            
                <a href="JS-3this-call-apply-bind.html">
            
                    
                    3this-call-apply-bind
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.8" data-path="JS-4数据类型转换.html">
            
                <a href="JS-4数据类型转换.html">
            
                    
                    4数据类型转换
            
                </a>
            

            
        </li>
    
        <li class="chapter active" data-level="1.4.9" data-path="JS-5跨域.html">
            
                <a href="JS-5跨域.html">
            
                    
                    5跨域
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.10" data-path="6Ajax.md">
            
                <span>
            
                    
                    6Ajax
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.11" data-path="JS-7函数.html">
            
                <a href="JS-7函数.html">
            
                    
                    7函数
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.12" data-path="JS-8Date日期.html">
            
                <a href="JS-8Date日期.html">
            
                    
                    8Date日期
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.13" data-path="JS获取标签宽高及实例.html">
            
                <a href="JS获取标签宽高及实例.html">
            
                    
                    JS获取标签宽高及实例
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.14" data-path="webpack教程.html">
            
                <a href="webpack教程.html">
            
                    
                    webpack教程
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.15" >
            
                <span>
            
                    
                    高级
            
                </span>
            

            
            <ul class="articles">
                
    
        <li class="chapter " data-level="1.4.15.1" data-path="advanced/常用的代码片段.md">
            
                <span>
            
                    
                    常用的代码片段
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.15.2" data-path="advanced/浏览器兼容.html">
            
                <a href="advanced/浏览器兼容.html">
            
                    
                    浏览器兼容
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.15.3" data-path="advanced/html-SEO搜索引擎优化.html">
            
                <a href="advanced/html-SEO搜索引擎优化.html">
            
                    
                    SEO搜索引擎优化
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.15.4" data-path="advanced/手机端页面开发.html">
            
                <a href="advanced/手机端页面开发.html">
            
                    
                    手机端页面开发
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.15.5" data-path="advanced/原生JS实现一些页面组件.html">
            
                <a href="advanced/原生JS实现一些页面组件.html">
            
                    
                    原生JS实现一些页面组件
            
                </a>
            

            
        </li>
    

            </ul>
            
        </li>
    
        <li class="chapter " data-level="1.4.16" >
            
                <span>
            
                    
                    dom
            
                </span>
            

            
            <ul class="articles">
                
    
        <li class="chapter " data-level="1.4.16.1" data-path="dom/dom-1节点的类型.html">
            
                <a href="dom/dom-1节点的类型.html">
            
                    
                    dom节点-1节点的类型
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.16.2" data-path="dom/dom-2节点的关系.html">
            
                <a href="dom/dom-2节点的关系.html">
            
                    
                    dom节点-2节点的关系
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.16.3" data-path="dom/dom-3节点的操作.html">
            
                <a href="dom/dom-3节点的操作.html">
            
                    
                    dom节点-3节点的操作
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.16.4" data-path="dom/dom-4-动态集合NodeLIst-HTMLCollection.html">
            
                <a href="dom/dom-4-动态集合NodeLIst-HTMLCollection.html">
            
                    
                    dom节点-4-HTMLCollection-NodeList
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.16.5" data-path="dom/dom-5Element.html">
            
                <a href="dom/dom-5Element.html">
            
                    
                    dom-5-Element
            
                </a>
            

            
        </li>
    

            </ul>
            
        </li>
    
        <li class="chapter " data-level="1.4.17" data-path="designPattern/设计模式文档.html">
            
                <a href="designPattern/设计模式文档.html">
            
                    
                    JavaScript设计模式
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.18" >
            
                <span>
            
                    
                    vue、react框架模板搭建
            
                </span>
            

            
            <ul class="articles">
                
    
        <li class="chapter " data-level="1.4.18.1" data-path="advanced/vue项目搭建.html">
            
                <a href="advanced/vue项目搭建.html">
            
                    
                    使用vue-cli搭建一个空项目
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.4.18.2" data-path="advanced/react项目搭建.html">
            
                <a href="advanced/react项目搭建.html">
            
                    
                    使用create-react-app搭建一个空项目
            
                </a>
            

            
        </li>
    

            </ul>
            
        </li>
    

            </ul>
            
        </li>
    
        <li class="chapter " data-level="1.5" >
            
                <span>
            
                    
                    CSS
            
                </span>
            

            
            <ul class="articles">
                
    
        <li class="chapter " data-level="1.5.1" data-path="../css/CSS-定位.html">
            
                <a href="../css/CSS-定位.html">
            
                    
                    position定位
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.5.2" data-path="../css/CSS常见样式下.html">
            
                <a href="../css/CSS常见样式下.html">
            
                    
                    常见样式下
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.5.3" data-path="../css/CSS深入浅出-1宽度与高度笔记.html">
            
                <a href="../css/CSS深入浅出-1宽度与高度笔记.html">
            
                    
                    深入浅出-1宽度与高度
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.5.4" data-path="../css/CSS深入浅出-2堆叠上下文.html">
            
                <a href="../css/CSS深入浅出-2堆叠上下文.html">
            
                    
                    深入浅出-2堆叠上下文
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.5.5" data-path="../css/CSS深入浅出-3icon全解.html">
            
                <a href="../css/CSS深入浅出-3icon全解.html">
            
                    
                    深入浅出-3icon全解
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.5.6" data-path="../css/CSS深入浅出-4移动端页面-响应式.md">
            
                <span>
            
                    
                    深入浅出-4移动端页面-响应式
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.5.7" data-path="../css/CSS深入浅出-5Flex布局.html">
            
                <a href="../css/CSS深入浅出-5Flex布局.html">
            
                    
                    深入浅出-5Flex布局
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.5.8" data-path="../css/CSS深入浅出-6布局套路.html">
            
                <a href="../css/CSS深入浅出-6布局套路.html">
            
                    
                    深入浅出-6布局套路
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.5.9" data-path="../css/CSS深入浅出-7BFC.html">
            
                <a href="../css/CSS深入浅出-7BFC.html">
            
                    
                    深入浅出-7BFC
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.5.10" data-path="../css/CSS深入浅出-8动态REM.html">
            
                <a href="../css/CSS深入浅出-8动态REM.html">
            
                    
                    深入浅出-8动态REM
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.5.11" data-path="../css/CSS-浏览器兼容.html">
            
                <a href="../css/CSS-浏览器兼容.html">
            
                    
                    浏览器兼容
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.5.12" data-path="../css/CSS垂直水平居中.html">
            
                <a href="../css/CSS垂直水平居中.html">
            
                    
                    垂直水平居中
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.5.13" data-path="../css/Normalize.css和Reset CSS.html">
            
                <a href="../css/Normalize.css和Reset CSS.html">
            
                    
                    Normalize.css和Reset CSS
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.5.14" data-path="../css/LESS-SCSS语法.html">
            
                <a href="../css/LESS-SCSS语法.html">
            
                    
                    LESS-SCSS语法
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.5.15" data-path="../css/CSS常用代码片段.html">
            
                <a href="../css/CSS常用代码片段.html">
            
                    
                    CSS常用代码片段
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.5.16" data-path="../css/CSS选择器.html">
            
                <a href="../css/CSS选择器.html">
            
                    
                    CSS选择器
            
                </a>
            

            
        </li>
    

            </ul>
            
        </li>
    
        <li class="chapter " data-level="1.6" >
            
                <span>
            
                    
                    其他
            
                </span>
            

            
            <ul class="articles">
                
    
        <li class="chapter " data-level="1.6.1" data-path="../other/前端笔试编程题.html">
            
                <a href="../other/前端笔试编程题.html">
            
                    
                    前端笔试编程题
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.6.2" data-path="../other/前端面试题.html">
            
                <a href="../other/前端面试题.html">
            
                    
                    前端面试题
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.6.3" data-path="../other/浏览器从输入URL到出现页面过程.html">
            
                <a href="../other/浏览器从输入URL到出现页面过程.html">
            
                    
                    浏览器从输入URL到出现页面过程
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.6.4" data-path="../other/饥人谷课堂笔记.html">
            
                <a href="../other/饥人谷课堂笔记.html">
            
                    
                    饥人谷课堂笔记
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.6.5" data-path="../other/饥人谷每天一到面试题.html">
            
                <a href="../other/饥人谷每天一到面试题.html">
            
                    
                    饥人谷每天一到面试题
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.6.6" data-path="../other/Emmet语法(HTML标签补全">
            
                <span>
            
                    
                    Emmet语法(HTML标签补全)
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.6.7" data-path="../JS-需要编写的文档.html">
            
                <a href="../JS-需要编写的文档.html">
            
                    
                    JS-需要编写的文档
            
                </a>
            

            
        </li>
    
        <li class="chapter " data-level="1.6.8" data-path="../other/z-临时文件.html">
            
                <a href="../other/z-临时文件.html">
            
                    
                    z-临时文件
            
                </a>
            

            
        </li>
    

            </ul>
            
        </li>
    

    

    <li class="divider"></li>

    <li>
        <a href="https://www.gitbook.com" target="blank" class="gitbook-link">
            Published with GitBook
        </a>
    </li>
</ul>


                </nav>
            
        
    </div>

    <div class="book-body">
        
            <div class="body-inner">
                
                    

<div class="book-header" role="navigation">
    

    <!-- Title -->
    <h1>
        <i class="fa fa-circle-o-notch fa-spin"></i>
        <a href="../.." >5跨域</a>
    </h1>
</div>




                    <div class="page-wrapper" tabindex="-1" role="main">
                        <div class="page-inner">
                            
<div id="book-search-results">
    <div class="search-noresults">
    
                                <section class="normal markdown-section">
                                
                                <h2 id="&#x6D4F;&#x89C8;&#x5668;&#x963B;&#x6B62;&#x8DE8;&#x57DF;&#x7684;&#x76EE;&#x7684;">&#x6D4F;&#x89C8;&#x5668;&#x963B;&#x6B62;&#x8DE8;&#x57DF;&#x7684;&#x76EE;&#x7684;</h2>
<ul>
<li><p>&#x5B89;&#x5168;&#x95EE;&#x9898;</p>
<p>&#x5982;CSRF&#x5C31;&#x662F;&#x5229;&#x7528;&#x8DE8;&#x57DF;&#x653B;&#x51FB;&#x7684;&#x3002;</p>
<p>CSRF&#xFF08;Cross-site request forgery&#xFF09;&#xFF0C;&#x4E2D;&#x6587;&#x540D;&#x79F0;&#xFF1A;&#x8DE8;&#x7AD9;&#x8BF7;&#x6C42;&#x4F2A;&#x9020;</p>
<p>CSRF&#x653B;&#x51FB;&#xFF1A;&#x653B;&#x51FB;&#x8005;&#x76D7;&#x7528;&#x4E86;&#x4F60;&#x7684;&#x8EAB;&#x4EFD;&#xFF0C;&#x4EE5;&#x4F60;&#x7684;&#x540D;&#x4E49;&#x53D1;&#x9001;&#x6076;&#x610F;&#x8BF7;&#x6C42;&#x3002;CSRF&#x80FD;&#x591F;&#x505A;&#x7684;&#x4E8B;&#x60C5;&#x5305;&#x62EC;&#xFF1A;&#x4EE5;&#x4F60;&#x540D;&#x4E49;&#x53D1;&#x9001;&#x90AE;&#x4EF6;&#xFF0C;&#x53D1;&#x6D88;&#x606F;&#xFF0C;&#x76D7;&#x53D6;&#x4F60;&#x7684;&#x8D26;&#x53F7;&#xFF0C;&#x751A;&#x81F3;&#x4E8E;&#x8D2D;&#x4E70;&#x5546;&#x54C1;&#xFF0C;&#x865A;&#x62DF;&#x8D27;&#x5E01;&#x8F6C;&#x8D26;......&#x9020;&#x6210;&#x7684;&#x95EE;&#x9898;&#x5305;&#x62EC;&#xFF1A;&#x4E2A;&#x4EBA;&#x9690;&#x79C1;&#x6CC4;&#x9732;&#x4EE5;&#x53CA;&#x8D22;&#x4EA7;&#x5B89;&#x5168;&#x3002;</p>
<p>&#x539F;&#x7406;&#xFF1A; &#x6D4F;&#x89C8;&#x5668;&#x5728;&#x53D1;&#x9001;&#x8BF7;&#x6C42;&#x7684;&#x65F6;&#x5019;&#xFF0C;&#x4F1A;&#x5728;&#x8BF7;&#x6C42;&#x4E2D;&#x9644;&#x52A0;cookie&#x4FE1;&#x606F;&#xFF0C;&#x90A3;&#x4E48;&#x6839;&#x636E;cookie&#x4FE1;&#x606F;&#xFF0C;&#x670D;&#x52A1;&#x5668;&#x5C31;&#x4F1A;&#x4EFB;&#x52A1;&#x662F;&#x672C;&#x4EBA;&#x4EB2;&#x81EA;&#x64CD;&#x4F5C;&#xFF0C;&#x524D;&#x63D0;&#x662F;&#x7528;&#x6237;&#x767B;&#x9646;&#x8FC7;&#x8FD9;&#x4E2A;&#x7F51;&#x7AD9;&#x3002;</p>
</li>
<li><p>&#x7981;&#x6B62;&#x90A3;&#x4E9B;&#x4E0D;&#x5141;&#x8BB8;&#x8DE8;&#x57DF;&#x8C03;&#x7528;&#x5176;&#x4ED6;&#x9875;&#x9762;&#x7684;&#x5BF9;&#x8C61;&#x3002;</p>
<p>&#x200B;</p>
</li>
</ul>
<h2 id="&#x8DE8;&#x57DF;&#x4ECB;&#x7ECD;">&#x8DE8;&#x57DF;&#x4ECB;&#x7ECD;</h2>
<p>&#x5F53;&#x4E00;&#x4E2A;&#x8D44;&#x6E90;&#x4ECE;&#x4E0E;&#x8BE5;&#x8D44;&#x6E90;&#x672C;&#x8EAB;&#x6240;&#x5728;&#x7684;&#x670D;&#x52A1;&#x5668;&#x4E0D;&#x540C;&#x7684;&#x57DF;&#x6216;&#x7AEF;&#x53E3;&#x8BF7;&#x6C42;&#x4E00;&#x4E2A;&#x8D44;&#x6E90;&#x65F6;&#xFF0C;&#x8D44;&#x6E90;&#x4F1A;&#x53D1;&#x8D77;&#x4E00;&#x4E2A;<strong>&#x8DE8;&#x57DF; HTTP &#x8BF7;&#x6C42;</strong>&#x3002;</p>
<p>&#x51FA;&#x4E8E;&#x5B89;&#x5168;&#x539F;&#x56E0;&#xFF0C;<strong>&#x6D4F;&#x89C8;&#x5668;&#x9650;&#x5236;&#x4ECE;&#x811A;&#x672C;&#x5185;&#x53D1;&#x8D77;&#x7684;&#x8DE8;&#x6E90;HTTP&#x8BF7;&#x6C42;&#x3002;</strong> &#x4F8B;&#x5982;&#xFF0C;XMLHttpRequest&#x548C;Fetch API&#x9075;&#x5FAA;&#x540C;&#x6E90;&#x7B56;&#x7565;&#x3002; &#x8FD9;&#x610F;&#x5473;&#x7740;&#x4F7F;&#x7528;&#x8FD9;&#x4E9B;API&#x7684;Web&#x5E94;&#x7528;&#x7A0B;&#x5E8F;&#x53EA;&#x80FD;&#x4ECE;&#x52A0;&#x8F7D;&#x5E94;&#x7528;&#x7A0B;&#x5E8F;&#x7684;&#x540C;&#x4E00;&#x4E2A;&#x57DF;&#x8BF7;&#x6C42;HTTP&#x8D44;&#x6E90;&#xFF0C;&#x9664;&#x975E;&#x4F7F;&#x7528;CORS&#x5934;&#x6587;&#x4EF6;&#x3002;</p>
<p><a href="https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Access_control_CORS" target="_blank">HTTP&#x8BBF;&#x95EE;&#x63A7;&#x5236; MDN</a></p>
<p>&#x5F53;&#x8BBF;&#x95EE;API&#x53D1;&#x751F;&#x8DE8;&#x57DF;&#x7684;&#x65F6;&#x5019;&#xFF0C;&#x6D4F;&#x89C8;&#x5668;&#x4F1A;&#x62A5;&#x5982;&#x4E0B;&#x9519;&#x8BEF;&#xFF1A;</p>
<pre><code class="lang-html">Failed to load http://api.douban.com/v2/movie/top250: No &apos;Access-Control-Allow-Origin&apos; header is present on the requested resource. Origin &apos;http://127.0.0.1:8080&apos; is therefore not allowed access.
</code></pre>
<p>&#x8DE8;&#x57DF;&#x53D1;&#x751F;&#x65F6;&#xFF1A; &#x6570;&#x636E;&#x5DF2;&#x7ECF;&#x8FD4;&#x56DE;&#x4E86;(API&#x6B63;&#x5E38;&#x8FD4;&#x56DE;&#x4E86;&#x7ED3;&#x679C;)&#xFF0C;&#x4F46;&#x662F;&#x6D4F;&#x89C8;&#x5668;&#x68C0;&#x67E5;&#x53D1;&#x73B0;&#x4E0D;&#x662F;&#x540C;&#x6E90;&#x7684;&#xFF0C;&#x90A3;&#x4E48;&#x963B;&#x6B62;&#x4E86;&#x3002;</p>
<h2 id="&#x540C;&#x6E90;&#x7B56;&#x7565;same-origin-policy">&#x540C;&#x6E90;&#x7B56;&#x7565;(Same origin Policy)</h2>
<p>&#x540C;&#x6E90;&#x7B56;&#x7565;&#x662F;&#x6D4F;&#x89C8;&#x5668;&#x81EA;&#x5DF1;&#x7684;&#x884C;&#x4E3A;&#xFF0C;&#x5982;&#x679C;&#x8BBF;&#x95EE;&#x63A5;&#x53E3;&#x4E0D;&#x662F;&#x5728;&#x6D4F;&#x89C8;&#x5668;&#x4E0A;&#x53D1;&#x751F;&#x5219;&#x4E0D;&#x4F1A;&#x6709;&#x8FD9;&#x4E2A;&#x95EE;&#x9898;&#x4EA7;&#x751F;&#x3002;</p>
<p>&#x6D4F;&#x89C8;&#x5668;&#x51FA;&#x4E8E;&#x5B89;&#x5168;&#x65B9;&#x9762;&#x7684;&#x8003;&#x8651;&#xFF0C;&#x53EA;&#x5141;&#x8BB8;&#x4E0E;&#x672C;&#x57DF;&#x4E0B;&#x7684;&#x63A5;&#x53E3;&#x4EA4;&#x4E92;&#x3002;&#x4E0D;&#x540C;&#x6E90;&#x7684;&#x5BA2;&#x6237;&#x7AEF;&#x811A;&#x672C;&#x5728;&#x6CA1;&#x6709;&#x660E;&#x786E;&#x6388;&#x6743;&#x7684;&#x60C5;&#x51B5;&#x4E0B;&#xFF0C;&#x4E0D;&#x80FD;&#x8BFB;&#x5199;&#x5BF9;&#x65B9;&#x7684;&#x8D44;&#x6E90;&#x3002;</p>
<p>&#x5982;&#x679C;&#x4E24;&#x4E2A;&#x9875;&#x9762;&#x7684;&#x534F;&#x8BAE;&#xFF0C;&#x7AEF;&#x53E3;&#xFF08;&#x5982;&#x679C;&#x6709;&#x6307;&#x5B9A;&#xFF09;&#x548C;&#x57DF;&#x540D;&#x90FD;&#x76F8;&#x540C;&#xFF0C;&#x5219;&#x4E24;&#x4E2A;&#x9875;&#x9762;&#x5177;&#x6709;&#x76F8;&#x540C;&#x7684;<strong>&#x6E90;</strong>&#x3002;</p>
<ul>
<li>&#x540C;&#x534F;&#x8BAE;&#xFF1A;&#x5982;&#x90FD;&#x662F;http&#x6216;&#x8005;https</li>
<li>&#x540C;&#x57DF;&#x540D;&#xFF1A;&#x5982;&#x90FD;&#x662F;<code>http://www.abc.com/a.html</code> &#x548C;<code>http://www.abc.com/b.html</code></li>
<li>&#x540C;&#x7AEF;&#x53E3;&#xFF1A;&#x5982;&#x90FD;&#x662F;80&#x7AEF;&#x53E3;</li>
</ul>
<p>&#x76F8;&#x5BF9;<code>http://store.company.com/dir/page.html</code>&#x540C;&#x6E90;&#x68C0;&#x6D4B;&#x7684;&#x793A;&#x4F8B;:</p>
<table>
<thead>
<tr>
<th>URL</th>
<th>&#x7ED3;&#x679C;</th>
<th>&#x539F;&#x56E0;</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>http://store.company.com/dir2/other.html</code></td>
<td>&#x6210;&#x529F;</td>
<td></td>
</tr>
<tr>
<td><code>http://store.company.com/dir/inner/another.html</code></td>
<td>&#x6210;&#x529F;</td>
<td></td>
</tr>
<tr>
<td><code>https://store.company.com/secure.html</code></td>
<td>&#x5931;&#x8D25;</td>
<td>&#x4E0D;&#x540C;&#x534F;&#x8BAE; ( https&#x548C;http )</td>
</tr>
<tr>
<td><code>http://store.company.com:81/dir/etc.html</code></td>
<td>&#x5931;&#x8D25;</td>
<td>&#x4E0D;&#x540C;&#x7AEF;&#x53E3; ( 81&#x548C;80)</td>
</tr>
<tr>
<td><code>http://news.company.com/dir/other.html</code></td>
<td>&#x5931;&#x8D25;</td>
<td>&#x4E0D;&#x540C;&#x57DF;&#x540D; ( news&#x548C;store )</td>
</tr>
</tbody>
</table>
<p><a href="https://developer.mozilla.org/zh-CN/docs/Web/Security/Same-origin_policy" target="_blank">&#x6D4F;&#x89C8;&#x5668;&#x7684;&#x540C;&#x6E90;&#x7B56;&#x7565; MDN</a></p>
<h2 id="&#x4E00;&#x4E2A;&#x8DE8;&#x57DF;&#x7684;&#x4F8B;&#x5B50;">&#x4E00;&#x4E2A;&#x8DE8;&#x57DF;&#x7684;&#x4F8B;&#x5B50;</h2>
<blockquote>
<p>&#x670D;&#x52A1;&#x5668;&#x7AEF;</p>
</blockquote>
<ol>
<li><p>&#x5B89;&#x88C5;node.js</p>
<p>&#x5982;&#x679C;&#x6CA1;&#x6709;&#x6CA1;&#x6709;&#x5B89;&#x88C5;nodejs,&#x90A3;&#x4E48;&#x53BB;&#x5B98;&#x7F51;&#x4E0B;&#x8F7D;&#xFF1A;<a href="https://nodejs.org/en/download/" target="_blank">https://nodejs.org/en/download/</a></p>
</li>
<li><p>&#x521B;&#x5EFA;&#x4E00;&#x4E2A;&#x76EE;&#x5F55;&#xFF0C;&#x5728;&#x8FD9;&#x4E2A;&#x76EE;&#x5F55;&#x4E2D;&#x521B;&#x5EFA;&#x4E00;&#x4E2A;server.js&#x6587;&#x4EF6;&#xFF0C;&#x5185;&#x5BB9;&#x5982;&#x4E0B;&#xFF1A;</p>
<pre><code class="lang-javascript"><span class="hljs-keyword">var</span> http = <span class="hljs-built_in">require</span>(<span class="hljs-string">&apos;http&apos;</span>)
<span class="hljs-keyword">var</span> fs = <span class="hljs-built_in">require</span>(<span class="hljs-string">&apos;fs&apos;</span>)
<span class="hljs-keyword">var</span> path = <span class="hljs-built_in">require</span>(<span class="hljs-string">&apos;path&apos;</span>)
<span class="hljs-keyword">var</span> url = <span class="hljs-built_in">require</span>(<span class="hljs-string">&apos;url&apos;</span>)

http.createServer(<span class="hljs-function"><span class="hljs-keyword">function</span>(<span class="hljs-params">req, res</span>)</span>{

  <span class="hljs-keyword">var</span> pathObj = url.parse(req.url, <span class="hljs-literal">true</span>)

  <span class="hljs-keyword">switch</span> (pathObj.pathname) {
    <span class="hljs-keyword">case</span> <span class="hljs-string">&apos;/getWeather&apos;</span>:
      res.end(<span class="hljs-built_in">JSON</span>.stringify({beijing: <span class="hljs-string">&apos;sunny&apos;</span>}))
      <span class="hljs-keyword">break</span>;

    <span class="hljs-keyword">default</span>:
      fs.readFile(path.join(__dirname, pathObj.pathname), <span class="hljs-function"><span class="hljs-keyword">function</span>(<span class="hljs-params">e, data</span>)</span>{
        <span class="hljs-keyword">if</span>(e){
          res.writeHead(<span class="hljs-number">404</span>, <span class="hljs-string">&apos;not found&apos;</span>)
          res.end(<span class="hljs-string">&apos;&lt;h1&gt;404 Not Found&lt;/h1&gt;&apos;</span>)
        }<span class="hljs-keyword">else</span>{
          res.end(data)
        }
      }) 
  }
}).listen(<span class="hljs-number">8080</span>)
</code></pre>
</li>
<li><p>&#x7EC8;&#x7AEF;&#x6253;&#x5F00;&#x8FD9;&#x4E2A;&#x9879;&#x76EE;&#x76EE;&#x5F55;&#xFF0C;&#x8FD0;&#x884C;<code>node server.js</code>&#x542F;&#x52A8;&#x670D;&#x52A1;&#xFF0C;&#x670D;&#x52A1;&#x5730;&#x5740;&#xFF1A;<code>http://localhost:8080/</code></p>
</li>
</ol>
<blockquote>
<p> &#x9875;&#x9762;&#x7AEF;&#x670D;&#x52A1;</p>
</blockquote>
<ol>
<li><p>&#x5B89;&#x88C5;http-server&#x670D;&#x52A1;</p>
<p>&#x5982;&#x679C;&#x6CA1;&#x6709;&#x5B89;&#x88C5;&#xFF0C;&#x7EC8;&#x7AEF;&#x8FD0;&#x884C;&#xFF1A;<code>npm install http-server -g</code>&#xFF0C; npm&#x547D;&#x4EE4;&#x662F;&#x5B89;&#x88C5;nodeJS&#x5E26;&#x7684;&#x3002;</p>
<p>http-server&#x4ECB;&#x7ECD;&#xFF1A;<a href="https://github.com/indexzero/http-server" target="_blank">https://github.com/indexzero/http-server</a></p>
</li>
<li><p>&#x5728;&#x4E0A;&#x9762;&#x7684;&#x76EE;&#x5F55;&#x4E2D;&#x65B0;&#x5EFA;&#x4E00;&#x4E2A;index.html&#x6587;&#x4EF6;&#xFF0C;&#x4EE3;&#x7801;&#x5982;&#x4E0B;&#xFF1A;</p>
<pre><code>&lt;h1&gt;&#x9965;&#x4EBA;&#x8C37;&lt;/h1&gt;
&lt;script&gt;
  var xhr = new XMLHttpRequest()
  xhr.open(&apos;GET&apos;,&apos;http://localhost:8080/getWeather&apos;, true)
  xhr.send()
  xhr.onload = function(){
    console.log(xhr.responseText)
  }
&lt;/script&gt;
</code></pre></li>
<li><p>&#x4F7F;&#x7528;http-server&#x547D;&#x4EE4;&#x542F;&#x52A8;web&#x670D;&#x52A1;</p>
<pre><code>http-server
Starting up http-server, serving ./
Available on:
  http://127.0.0.1:8081
  http://192.168.43.183:8081
Hit CTRL-C to stop the server
</code></pre><p>&#x200B;</p>
</li>
</ol>
<blockquote>
<p>&#x8BBF;&#x95EE;&#x9875;&#x9762;&#x5219;&#x63D0;&#x793A;&#x4EA7;&#x751F;&#x8DE8;&#x57DF;&#x95EE;&#x9898;</p>
</blockquote>
<p>&#x5F53;&#x5728;&#x6D4F;&#x89C8;&#x5668;&#x4E2D;&#x6253;&#x5F00;&#xFF1A;<code>http://127.0.0.1:8081</code>&#x9875;&#x9762;&#x662F;&#xFF0C;&#x6D4F;&#x89C8;&#x5668;&#x5C31;&#x662F;&#x63D0;&#x793A;&#x5982;&#x4E0B;&#x9519;&#x8BEF;&#xFF1A;</p>
<pre><code>Failed to load http://localhost:8080/getWeather: No &apos;Access-Control-Allow-Origin&apos; header is present on the requested resource. Origin &apos;http://127.0.0.1:8081&apos; is therefore not allowed access.
</code></pre><h2 id="&#x5982;&#x4F55;&#x8FDB;&#x884C;&#x8DE8;&#x57DF;&#x8BBF;&#x95EE;&#xFF1F;">&#x5982;&#x4F55;&#x8FDB;&#x884C;&#x8DE8;&#x57DF;&#x8BBF;&#x95EE;&#xFF1F;</h2>
<h3 id="&#x4F7F;&#x7528;jsonp&#x6765;&#x5B9E;&#x73B0;&#x8DE8;&#x57DF;&#x8BBF;&#x95EE;">&#x4F7F;&#x7528;JSONP&#x6765;&#x5B9E;&#x73B0;&#x8DE8;&#x57DF;&#x8BBF;&#x95EE;</h3>
<h4 id="jsonp&#x7684;&#x539F;&#x7406;">JSONP&#x7684;&#x539F;&#x7406;</h4>
<p><code>JSONP</code>&#x662F;<code>JSON with Padding</code>&#x7684;&#x7B80;&#x79F0;&#xFF0C;&#x4E00;&#x822C;&#x7528;&#x6765;&#x89E3;&#x51B3;<code>Ajax</code>&#x8DE8;&#x57DF;&#x7684;&#x95EE;&#x9898;&#x3002;&#x5B83;&#x662F;&#x8FD9;&#x6837;&#x4EA7;&#x751F;&#x7684;&#xFF1A;</p>
<ol>
<li>&#x9875;&#x9762;&#x4E0A;&#x8C03;&#x7528;<code>js</code>&#x6587;&#x4EF6;&#x65F6;&#x4E0D;&#x53D7;&#x8DE8;&#x57DF;&#x7684;&#x5F71;&#x54CD;&#xFF0C;&#x800C;&#x4E14;&#xFF0C;&#x51E1;&#x662F;&#x62E5;&#x6709;src&#x5C5E;&#x6027;&#x7684;&#x6807;&#x7B7E;&#x90FD;&#x62E5;&#x6709;&#x8DE8;&#x57DF;&#x7684;&#x80FD;&#x529B;&#xFF0C;&#x6BD4;&#x5982;<code>&lt;script&gt;</code>&#x3001;<code>&lt;img&gt;</code>&#x3001;<code>&lt;iframe&gt;</code>&#x3002;</li>
<li>&#x53EF;&#x4EE5;&#x5728;&#x8FDC;&#x7A0B;&#x670D;&#x52A1;&#x5668;&#x4E0A;&#x628A;&#x6570;&#x636E;&#x88C5;&#x8FDB;<code>js</code>&#x683C;&#x5F0F;&#x7684;&#x6587;&#x4EF6;&#x91CC;&#xFF0C;&#x4F9B;&#x5BA2;&#x6237;&#x7AEF;&#x8C03;&#x7528;&#x5904;&#x7406;&#xFF0C;&#x5B9E;&#x73B0;&#x8DE8;&#x57DF;&#x3002;</li>
<li>&#x76EE;&#x524D;&#x6700;&#x5E38;&#x7528;&#x7684;&#x6570;&#x636E;&#x4EA4;&#x6362;&#x65B9;&#x5F0F;&#x662F;<code>JSON</code>&#xFF0C;&#x5BA2;&#x6237;&#x7AEF;&#x901A;&#x8FC7;&#x8C03;&#x7528;&#x8FDC;&#x7A0B;&#x670D;&#x52A1;&#x5668;&#x4E0A;&#x52A8;&#x6001;&#x751F;&#x6210;&#x7684;<code>js</code>&#x683C;&#x5F0F;&#x6587;&#x4EF6;&#xFF08;&#x4E00;&#x822C;&#x4EE5;<code>JSON</code>&#x540E;&#x7F00;&#xFF09;&#x3002;</li>
<li>&#x5BA2;&#x6237;&#x7AEF;&#x6210;&#x529F;&#x8C03;&#x7528;<code>JSON</code>&#x6587;&#x4EF6;&#x540E;&#xFF0C;&#x5BF9;&#x5176;&#x8FDB;&#x884C;&#x5904;&#x7406;&#x3002;</li>
<li>&#x4E3A;&#x4E86;&#x4FBF;&#x4E8E;&#x5BA2;&#x6237;&#x7AEF;&#x4F7F;&#x7528;&#x6570;&#x636E;&#xFF0C;&#x9010;&#x6E10;&#x5F62;&#x6210;&#x4E86;&#x4E00;&#x79CD;&#x975E;&#x6B63;&#x5F0F;&#x4F20;&#x8F93;&#x534F;&#x8BAE;&#xFF0C;&#x4EBA;&#x4EEC;&#x628A;&#x5B83;&#x79F0;&#x4F5C;<code>JSONP</code>&#xFF0C;&#x8BE5;&#x534F;&#x8BAE;&#x7684;&#x4E00;&#x4E2A;&#x8981;&#x70B9;&#x5C31;&#x662F;&#x5141;&#x8BB8;&#x7528;&#x6237;&#x4F20;&#x9012;&#x4E00;&#x4E2A;<code>callback</code>&#x53C2;&#x6570;&#x7ED9;&#x670D;&#x52A1;&#x7AEF;&#xFF0C;&#x7136;&#x540E;&#x670D;&#x52A1;&#x7AEF;&#x8FD4;&#x56DE;&#x6570;&#x636E;&#x65F6;&#x4F1A;&#x5C06;&#x8FD9;&#x4E2A;<code>callback</code>&#x53C2;&#x6570;&#x4F5C;&#x4E3A;&#x51FD;&#x6570;&#x540D;&#x6765;&#x5305;&#x88F9;&#x4F4F;<code>JSON</code>&#x6570;&#x636E;&#xFF0C;&#x8FD9;&#x6837;&#x5BA2;&#x6237;&#x7AEF;&#x5C31;&#x53EF;&#x4EE5;&#x968F;&#x610F;&#x5B9A;&#x5236;&#x81EA;&#x5DF1;&#x7684;&#x51FD;&#x6570;&#x6765;&#x81EA;&#x52A8;&#x5904;&#x7406;&#x8FD4;&#x56DE;&#x6570;&#x636E;&#x4E86;&#x3002;</li>
</ol>
<p><a href="https://segmentfault.com/a/1190000007232373" target="_blank">&#x6D45;&#x8C08; JSONP &#x7684;&#x539F;&#x7406;&#x4E0E;&#x5B9E;&#x73B0;</a></p>
<h4 id="jsonp&#x7684;&#x5B9E;&#x73B0;">JSONP&#x7684;&#x5B9E;&#x73B0;</h4>
<ol>
<li>&#x5728;&#x9875;&#x9762;&#x4E2D;&#x58F0;&#x660E;&#x4E00;&#x4E2A;&#x51FD;&#x6570;&#xFF0C;&#x7136;&#x540E;&#x5199;&#x4E00;&#x4E2A;script &#x6807;&#x7B7E;&#xFF0C;&#x6807;&#x7B7E;&#x91CC;&#x9762;&#x7684;src&#x94FE;&#x63A5;&#x4E3A;API&#x63A5;&#x53E3;&#xFF0C;&#x901A;&#x8FC7;&#x63A5;&#x53E3;&#x4F20;&#x53C2;&#x7684;&#x65B9;&#x5F0F;&#x628A;&#x51FD;&#x6570;&#x540D;&#x5199;&#x4E0A;&#x3002;</li>
<li>&#x540E;&#x53F0;API&#x5728;&#x89E3;&#x6790;&#x5230;&#x51FD;&#x6570;&#x540D;&#x540E;&#xFF0C;&#x4F1A;&#x628A;&#x8FD4;&#x56DE;&#x7684;&#x6570;&#x636E;&#x62FC;&#x63A5;&#x6210;&#x51FD;&#x6570;&#x53C2;&#x6570;<code>function(data)</code>,&#x7136;&#x540E;&#x8FD4;&#x56DE;&#x7ED9;&#x9875;&#x9762;&#x3002;</li>
<li>&#x9875;&#x9762;&#x5728;&#x52A0;&#x8F7D;&#x5B8C;&#x811A;&#x672C;&#x540E;&#xFF0C;&#x4F1A;&#x5F53;JS&#x6587;&#x4EF6;&#x53BB;&#x6267;&#x884C;&#xFF0C;&#x90A3;&#x4E48;&#x5C31;&#x76F8;&#x5F53;&#x4E8E;&#x8C03;&#x7528;&#x51FD;&#x6570;&#xFF0C;&#x6B64;&#x65F6;&#x9875;&#x9762;&#x58F0;&#x660E;&#x7684;&#x51FD;&#x6570;&#x5C31;&#x53EF;&#x4EE5;&#x5904;&#x7406;API&#x8FD4;&#x56DE;&#x7684;&#x6570;&#x636E;&#x4E86;&#x3002;</li>
<li>&#x9700;&#x8981;&#x524D;&#x7AEF;&#x3001;&#x540E;&#x7AEF;&#x5171;&#x540C;&#x914D;&#x5408;&#x3002;</li>
</ol>
<p>&#x4E00;&#x4E2A;&#x4F8B;&#x5B50;&#xFF1A;</p>
<p>server.js</p>
<pre><code class="lang-javascript">
<span class="hljs-keyword">var</span> http = <span class="hljs-built_in">require</span>(<span class="hljs-string">&apos;http&apos;</span>)
<span class="hljs-keyword">var</span> fs = <span class="hljs-built_in">require</span>(<span class="hljs-string">&apos;fs&apos;</span>)
<span class="hljs-keyword">var</span> path = <span class="hljs-built_in">require</span>(<span class="hljs-string">&apos;path&apos;</span>)
<span class="hljs-keyword">var</span> url = <span class="hljs-built_in">require</span>(<span class="hljs-string">&apos;url&apos;</span>)

http.createServer(<span class="hljs-function"><span class="hljs-keyword">function</span>(<span class="hljs-params">req, res</span>)</span>{
  <span class="hljs-keyword">var</span> pathObj = url.parse(req.url, <span class="hljs-literal">true</span>)

  <span class="hljs-keyword">switch</span> (pathObj.pathname) {
    <span class="hljs-keyword">case</span> <span class="hljs-string">&apos;/getNews&apos;</span>:
      <span class="hljs-keyword">var</span> news = [
        <span class="hljs-string">&quot;&#x7B2C;11&#x65E5;&#x524D;&#x77BB;&#xFF1A;&#x4E2D;&#x56FD;&#x51B2;&#x51FB;4&#x91D1; &#x535A;&#x5C14;&#x7279;&#x518D;&#x6218;200&#x7C73;&#x7FBD;&#x7403;&quot;</span>,
        <span class="hljs-string">&quot;&#x6B63;&#x76F4;&#x64AD;&#x67F4;&#x98DA;/&#x6D2A;&#x709C;&#x51FA;&#x6218; &#x7537;&#x53CC;&#x529B;&#x4E89;&#x4F1A;&#x5E08;&#x51B3;&#x8D5B;&quot;</span>,
        <span class="hljs-string">&quot;&#x5973;&#x6392;&#x5C06;&#x6B7B;&#x78D5;&#x5DF4;&#x897F;&#xFF01;&#x90CE;&#x5E73;&#x5B89;&#x6392;&#x7537;&#x966A;&#x7EC3;&#x6A21;&#x4EFF;&#x5BF9;&#x65B9;&#x6838;&#x5FC3;&quot;</span>
        ]
      res.setHeader(<span class="hljs-string">&apos;Content-Type&apos;</span>,<span class="hljs-string">&apos;text/json; charset=utf-8&apos;</span>)
      <span class="hljs-keyword">if</span>(pathObj.query.callback){
        res.end(pathObj.query.callback + <span class="hljs-string">&apos;(&apos;</span> + <span class="hljs-built_in">JSON</span>.stringify(news) + <span class="hljs-string">&apos;)&apos;</span>)
      }<span class="hljs-keyword">else</span>{
        res.end(<span class="hljs-built_in">JSON</span>.stringify(news))
      }

      <span class="hljs-keyword">break</span>;

    <span class="hljs-keyword">default</span>:
      fs.readFile(path.join(__dirname, pathObj.pathname), <span class="hljs-function"><span class="hljs-keyword">function</span>(<span class="hljs-params">e, data</span>)</span>{
        <span class="hljs-keyword">if</span>(e){
          res.writeHead(<span class="hljs-number">404</span>, <span class="hljs-string">&apos;not found&apos;</span>)
          res.end(<span class="hljs-string">&apos;&lt;h1&gt;404 Not Found&lt;/h1&gt;&apos;</span>)
        }<span class="hljs-keyword">else</span>{
          res.end(data)
        }
      }) 
  }
}).listen(<span class="hljs-number">8080</span>)
</code></pre>
<p>index.html</p>
<pre><code class="lang-html"><span class="hljs-meta">&lt;!DOCTYPE html&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">html</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">body</span>&gt;</span>
  <span class="hljs-tag">&lt;<span class="hljs-name">div</span> <span class="hljs-attr">class</span>=<span class="hljs-string">&quot;container&quot;</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-name">ul</span> <span class="hljs-attr">class</span>=<span class="hljs-string">&quot;news&quot;</span>&gt;</span>
    <span class="hljs-tag">&lt;/<span class="hljs-name">ul</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-name">button</span> <span class="hljs-attr">class</span>=<span class="hljs-string">&quot;show&quot;</span>&gt;</span>show news<span class="hljs-tag">&lt;/<span class="hljs-name">button</span>&gt;</span>
  <span class="hljs-tag">&lt;/<span class="hljs-name">div</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">script</span>&gt;</span><span class="javascript">
  <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">$</span>(<span class="hljs-params">id</span>)</span>{
    <span class="hljs-keyword">return</span> <span class="hljs-built_in">document</span>.querySelector(id);
  }
  $(<span class="hljs-string">&apos;.show&apos;</span>).addEventListener(<span class="hljs-string">&apos;click&apos;</span>, <span class="hljs-function"><span class="hljs-keyword">function</span>(<span class="hljs-params"></span>)</span>{
    <span class="hljs-keyword">var</span> script = <span class="hljs-built_in">document</span>.createElement(<span class="hljs-string">&apos;script&apos;</span>);
    script.src = <span class="hljs-string">&apos;http://127.0.0.1:8080/getNews?callback=appendHtml&apos;</span>;
    <span class="hljs-built_in">document</span>.head.appendChild(script);
    <span class="hljs-built_in">document</span>.head.removeChild(script);
  })
  <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">appendHtml</span>(<span class="hljs-params">news</span>)</span>{
    <span class="hljs-keyword">var</span> html = <span class="hljs-string">&apos;&apos;</span>;
    <span class="hljs-keyword">for</span>( <span class="hljs-keyword">var</span> i=<span class="hljs-number">0</span>; i&lt;news.length; i++){
      html += <span class="hljs-string">&apos;&lt;li&gt;&apos;</span> + news[i] + <span class="hljs-string">&apos;&lt;/li&gt;&apos;</span>;
    }
    <span class="hljs-built_in">console</span>.log(html);
    $(<span class="hljs-string">&apos;.news&apos;</span>).innerHTML = html;
  }
</span><span class="hljs-tag">&lt;/<span class="hljs-name">script</span>&gt;</span>
<span class="hljs-tag">&lt;/<span class="hljs-name">html</span>&gt;</span>
</code></pre>
<h3 id="cors-&#x8DE8;&#x57DF;&#x8D44;&#x6E90;&#x5171;&#x4EAB;&#xFF08;cross-origin-resource-sharing&#xFF09;">CORS &#x8DE8;&#x57DF;&#x8D44;&#x6E90;&#x5171;&#x4EAB;&#xFF08;Cross-Origin Resource Sharing&#xFF09;</h3>
<p>CORS&#x662F;&#x4E00;&#x4E2A;W3C&#x6807;&#x51C6;,&#x5B83;&#x5141;&#x8BB8;&#x6D4F;&#x89C8;&#x5668;&#x5411;&#x8DE8;&#x6E90;&#x670D;&#x52A1;&#x5668;&#xFF0C;&#x53D1;&#x51FA;<a href="http://www.ruanyifeng.com/blog/2012/09/xmlhttprequest_level_2.html" target="_blank"><code>XMLHttpRequest</code></a>&#x8BF7;&#x6C42;&#xFF0C;&#x4ECE;&#x800C;&#x514B;&#x670D;&#x4E86;AJAX&#x53EA;&#x80FD;<a href="http://www.ruanyifeng.com/blog/2016/04/same-origin-policy.html" target="_blank">&#x540C;&#x6E90;</a>&#x4F7F;&#x7528;&#x7684;&#x9650;&#x5236;&#x3002;</p>
<p>CORS&#x9700;&#x8981;&#x6D4F;&#x89C8;&#x5668;&#x548C;&#x670D;&#x52A1;&#x5668;&#x540C;&#x65F6;&#x652F;&#x6301;&#x3002;&#x76EE;&#x524D;&#xFF0C;&#x6240;&#x6709;&#x6D4F;&#x89C8;&#x5668;&#x90FD;&#x652F;&#x6301;&#x8BE5;&#x529F;&#x80FD;&#xFF0C;IE&#x6D4F;&#x89C8;&#x5668;&#x4E0D;&#x80FD;&#x4F4E;&#x4E8E;IE10&#x3002;</p>
<p>&#x6574;&#x4E2A;CORS&#x901A;&#x4FE1;&#x8FC7;&#x7A0B;&#xFF0C;&#x90FD;&#x662F;&#x6D4F;&#x89C8;&#x5668;&#x81EA;&#x52A8;&#x5B8C;&#x6210;&#xFF0C;&#x4E0D;&#x9700;&#x8981;&#x7528;&#x6237;&#x53C2;&#x4E0E;&#x3002;&#x6D4F;&#x89C8;&#x5668;&#x4E00;&#x65E6;&#x53D1;&#x73B0;AJAX&#x8BF7;&#x6C42;&#x8DE8;&#x6E90;&#xFF0C;&#x5C31;&#x4F1A;&#x81EA;&#x52A8;&#x6DFB;&#x52A0;&#x4E00;&#x4E9B;&#x9644;&#x52A0;&#x7684;&#x5934;&#x4FE1;&#x606F;&#xFF0C;&#x6709;&#x65F6;&#x8FD8;&#x4F1A;&#x591A;&#x51FA;&#x4E00;&#x6B21;&#x9644;&#x52A0;&#x7684;&#x8BF7;&#x6C42;&#xFF0C;&#x4F46;&#x7528;&#x6237;&#x4E0D;&#x4F1A;&#x6709;&#x611F;&#x89C9;&#x3002;</p>
<p>&#x56E0;&#x6B64;&#xFF0C;&#x5B9E;&#x73B0;CORS&#x901A;&#x4FE1;&#x7684;&#x5173;&#x952E;&#x662F;&#x670D;&#x52A1;&#x5668;&#x3002;&#x53EA;&#x8981;&#x670D;&#x52A1;&#x5668;&#x5B9E;&#x73B0;&#x4E86;CORS&#x63A5;&#x53E3;&#xFF0C;&#x5C31;&#x53EF;&#x4EE5;&#x8DE8;&#x6E90;&#x901A;&#x4FE1;&#x3002;</p>
<h4 id="cors&#x6B65;&#x9AA4;">CORS&#x6B65;&#x9AA4;</h4>
<ol>
<li><p>&#x6D4F;&#x89C8;&#x5668;&#x53D1;&#x73B0;&#x8DE8;&#x57DF;&#xFF0C;&#x5728;&#x8BF7;&#x6C42;&#x4E2D;&#x6DFB;&#x52A0;<code>Origin</code>&#x5B57;&#x6BB5;</p>
<p>&#x5F53;&#x4F7F;&#x7528;XMLHttpRequest&#x53D1;&#x9001;&#x8BF7;&#x6C42;&#x65F6;&#xFF0C;&#x6D4F;&#x89C8;&#x5668;&#x53D1;&#x73B0;&#x6709;&#x8DE8;&#x57DF;&#xFF0C;&#x4F1A;&#x81EA;&#x52A8;&#x5728;&#x8BF7;&#x6C42;&#x5934;&#x4E2D;&#x6DFB;&#x52A0;&#x4E00;&#x4E2A;<code>Origin</code>&#x5B57;&#x6BB5;&#xFF1A;</p>
<pre><code>// Request Headers
Host: localhost:8081
Origin: http://127.0.0.1:8081
Pragma: no-cache
</code></pre><p><code>Origin</code>&#x7528;&#x6765;&#x8BF4;&#x660E;&#x8BF7;&#x6C42;&#x6765;&#x81EA;&#x54EA;&#x4E2A;&#x6E90;&#xFF08;&#x534F;&#x8BAE; + &#x57DF;&#x540D; + &#x7AEF;&#x53E3;&#xFF09;&#x3002;&#x670D;&#x52A1;&#x5668;&#x6839;&#x636E;&#x8FD9;&#x4E2A;&#x503C;&#xFF0C;&#x51B3;&#x5B9A;&#x662F;&#x5426;&#x540C;&#x610F;&#x8FD9;&#x6B21;&#x8BF7;&#x6C42;&#x3002;</p>
</li>
<li><p>&#x670D;&#x52A1;&#x5668;&#x8BBE;&#x7F6E;&#x5141;&#x8BB8;&#x8DE8;&#x57DF;&#x7684;&#x5730;&#x5740;&#xFF1A;<code>Access-Control-Allow-Origin</code></p>
<p>&#x5982;&#x679C;&#x8BF7;&#x6C42;&#x4E2D;Origin&#x6307;&#x5B9A;&#x7684;&#x5730;&#x5740; <strong>&#x7981;&#x6B62;&#x8DE8;&#x57DF;</strong>&#xFF0C;&#x670D;&#x52A1;&#x5668;&#x4F1A;&#x8FD4;&#x56DE;&#x4E00;&#x4E2A;&#x6B63;&#x5E38;&#x7684;HTTP&#x76F8;&#x5E94;&#x3002;</p>
<p>&#x5982;&#x679C;&#x8BF7;&#x6C42;&#x4E2D;Origin&#x6307;&#x5B9A;&#x7684;&#x5730;&#x5740; <strong>&#x5141;&#x8BB8;&#x8DE8;&#x57DF;</strong>&#xFF0C;&#x670D;&#x52A1;&#x5668;&#x4F1A;&#x5728;&#x54CD;&#x5E94;&#x5934;&#x4E2D;&#x6DFB;&#x52A0;&#x51E0;&#x70B9;&#x5B57;&#x6BB5;&#xFF1A;</p>
<pre><code>Access-Control-Allow-Origin: http://localhost:8081
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: FooBar
</code></pre><p><strong>Access-Control-Allow-Origin</strong>: &#x5FC5;&#x987B;&#x5B57;&#x6BB5;&#xFF0C;&#x5B83;&#x7684;&#x503C;&#x8981;&#x4E48;&#x662F;&#x8BF7;&#x6C42;&#x65F6;<code>Origin</code>&#x5B57;&#x6BB5;&#x7684;&#x503C;&#xFF0C;&#x8981;&#x4E48;&#x662F;&#x4E00;&#x4E2A;<code>*</code>&#xFF0C;&#x8868;&#x793A;&#x63A5;&#x53D7;&#x4EFB;&#x610F;&#x57DF;&#x540D;&#x7684;&#x8BF7;&#x6C42;&#x3002;</p>
<p><strong>Access-Control-Allow-Credentials</strong>&#xFF1A;&#x53EF;&#x9009;&#x5B57;&#x6BB5;&#xFF0C;&#x5B83;&#x7684;&#x503C;&#x662F;&#x4E00;&#x4E2A;&#x5E03;&#x5C14;&#x503C;&#xFF0C;&#x8868;&#x793A;&#x662F;&#x5426;&#x5141;&#x8BB8;&#x53D1;&#x9001;Cookie&#x3002;</p>
<p><strong>Access-Control-Expose-Headers</strong>&#xFF1A;&#x53EF;&#x9009;&#x5B57;&#x6BB5;&#xFF0C;&#x8BBE;&#x7F6E;<code>XMLHttpRequest</code>&#x5BF9;&#x8C61;&#x7684;<code>getResponseHeader()</code>&#x65B9;&#x6CD5;&#x53EA;&#x80FD;&#x62FF;&#x5230;&#x5176;&#x4ED6;&#x5B57;&#x6BB5;&#x3002;</p>
</li>
</ol>
<h4 id="&#x4E00;&#x4E2A;cors&#x4F8B;&#x5B50;">&#x4E00;&#x4E2A;CORS&#x4F8B;&#x5B50;</h4>
<p>server.js</p>
<pre><code class="lang-javascript"><span class="hljs-keyword">var</span> http = <span class="hljs-built_in">require</span>(<span class="hljs-string">&apos;http&apos;</span>)
<span class="hljs-keyword">var</span> fs = <span class="hljs-built_in">require</span>(<span class="hljs-string">&apos;fs&apos;</span>)
<span class="hljs-keyword">var</span> path = <span class="hljs-built_in">require</span>(<span class="hljs-string">&apos;path&apos;</span>)
<span class="hljs-keyword">var</span> url = <span class="hljs-built_in">require</span>(<span class="hljs-string">&apos;url&apos;</span>)

http.createServer(<span class="hljs-function"><span class="hljs-keyword">function</span>(<span class="hljs-params">req, res</span>)</span>{
  <span class="hljs-keyword">var</span> pathObj = url.parse(req.url, <span class="hljs-literal">true</span>)

  <span class="hljs-keyword">switch</span> (pathObj.pathname) {
    <span class="hljs-keyword">case</span> <span class="hljs-string">&apos;/getNews&apos;</span>:
      <span class="hljs-keyword">var</span> news = [<span class="hljs-number">1</span>,<span class="hljs-number">2</span>,<span class="hljs-number">3</span>]
      res.setHeader(<span class="hljs-string">&apos;Access-Control-Allow-Origin&apos;</span>,<span class="hljs-string">&apos;http://localhost:8080&apos;</span>)
      <span class="hljs-comment">//res.setHeader(&apos;Access-Control-Allow-Origin&apos;,&apos;*&apos;)</span>
      res.end(<span class="hljs-built_in">JSON</span>.stringify(news))
      <span class="hljs-keyword">break</span>;
    <span class="hljs-keyword">default</span>:
      fs.readFile(path.join(__dirname, pathObj.pathname), <span class="hljs-function"><span class="hljs-keyword">function</span>(<span class="hljs-params">e, data</span>)</span>{
        <span class="hljs-keyword">if</span>(e){
          res.writeHead(<span class="hljs-number">404</span>, <span class="hljs-string">&apos;not found&apos;</span>)
          res.end(<span class="hljs-string">&apos;&lt;h1&gt;404 Not Found&lt;/h1&gt;&apos;</span>)
        }<span class="hljs-keyword">else</span>{
          res.end(data)
        }
      }) 
  }
}).listen(<span class="hljs-number">8080</span>)
</code></pre>
<p>index.html</p>
<pre><code class="lang-html"><span class="hljs-meta">&lt;!DOCTYPE html&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">html</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">body</span>&gt;</span>
  <span class="hljs-tag">&lt;<span class="hljs-name">div</span> <span class="hljs-attr">class</span>=<span class="hljs-string">&quot;container&quot;</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-name">ul</span> <span class="hljs-attr">class</span>=<span class="hljs-string">&quot;news&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">ul</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-name">button</span> <span class="hljs-attr">class</span>=<span class="hljs-string">&quot;show&quot;</span>&gt;</span>show news<span class="hljs-tag">&lt;/<span class="hljs-name">button</span>&gt;</span>
  <span class="hljs-tag">&lt;/<span class="hljs-name">div</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">script</span>&gt;</span><span class="javascript">
  $(<span class="hljs-string">&apos;.show&apos;</span>).addEventListener(<span class="hljs-string">&apos;click&apos;</span>, <span class="hljs-function"><span class="hljs-keyword">function</span>(<span class="hljs-params"></span>)</span>{
    <span class="hljs-keyword">var</span> xhr = <span class="hljs-keyword">new</span> XMLHttpRequest()
    xhr.open(<span class="hljs-string">&apos;GET&apos;</span>, <span class="hljs-string">&apos;http://127.0.0.1:8080/getNews&apos;</span>, <span class="hljs-literal">true</span>)
    xhr.send()
    xhr.onload = <span class="hljs-function"><span class="hljs-keyword">function</span>(<span class="hljs-params"></span>)</span>{
      appendHtml(<span class="hljs-built_in">JSON</span>.parse(xhr.responseText))
    }
  })
  <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">appendHtml</span>(<span class="hljs-params">news</span>)</span>{
    <span class="hljs-keyword">var</span> html = <span class="hljs-string">&apos;&apos;</span>
    <span class="hljs-keyword">for</span>( <span class="hljs-keyword">var</span> i=<span class="hljs-number">0</span>; i&lt;news.length; i++){
      html += <span class="hljs-string">&apos;&lt;li&gt;&apos;</span> + news[i] + <span class="hljs-string">&apos;&lt;/li&gt;&apos;</span>
    }
    $(<span class="hljs-string">&apos;.news&apos;</span>).innerHTML = html
  }
  <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">$</span>(<span class="hljs-params">selector</span>)</span>{
    <span class="hljs-keyword">return</span> <span class="hljs-built_in">document</span>.querySelector(selector)
  }
</span><span class="hljs-tag">&lt;/<span class="hljs-name">script</span>&gt;</span>
<span class="hljs-tag">&lt;/<span class="hljs-name">html</span>&gt;</span>
</code></pre>
<p><strong>&#x6CE8;&#xFF1A;</strong><code>http://localhost:8080</code> &#x548C;<code>http://127.0.0.1:8080</code>&#x4E0D;&#x540C;&#x6E90;&#x3002;</p>
<p><a href="http://www.ruanyifeng.com/blog/2016/04/cors.html" target="_blank">&#x8DE8;&#x57DF;&#x8D44;&#x6E90;&#x5171;&#x4EAB; CORS &#x8BE6;&#x89E3; &#x962E;&#x4E00;&#x5CF0;</a></p>
<h2 id="iframe&#x8DE8;&#x57DF;&#x65B9;&#x6CD5;">iframe&#x8DE8;&#x57DF;&#x65B9;&#x6CD5;</h2>
<p>&#x5F53;&#x9875;&#x9762;&#x4F7F;&#x7528;iframe&#x6807;&#x7B7E;&#x5185;&#x5D4C;&#x5176;&#x4ED6;&#x9875;&#x9762;&#x7684;&#x65F6;&#x5019;&#xFF0C;&#x90A3;&#x4E48;&#x6D4F;&#x89C8;&#x5668;&#x4F1A;&#x7981;&#x6B62;JS&#x64CD;&#x4F5C;&#x5185;&#x5D4C;&#x9875;&#x9762;&#x5143;&#x7D20;&#xFF0C;&#x53EA;&#x6709;&#x540C;&#x6E90;&#x7684;&#x9875;&#x9762;&#x624D;&#x5141;&#x8BB8;&#x64CD;&#x4F5C;&#x3002;</p>
<p>&#x5982;&#x679C;&#x60F3;&#x8981;&#x4E0D;&#x540C;&#x6E90;&#x7684;&#x9875;&#x9762;&#x53EF;&#x4EE5;&#x64CD;&#x4F5C;&#x90A3;&#x4E48;&#x53EF;&#x4F7F;&#x7528;&#x5982;&#x4E0B;&#x65B9;&#x6CD5;&#xFF1A;</p>
<h3 id="&#x964D;&#x57DF;&#xFF1A;documentdomain">&#x964D;&#x57DF;&#xFF1A;document.domain</h3>
<p>&#x5982;&#x679C;&#x4E24;&#x4E2A;&#x7A97;&#x53E3;&#x4E00;&#x7EA7;&#x57DF;&#x540D;&#x76F8;&#x540C;&#xFF0C;&#x53EA;&#x662F;&#x4E8C;&#x7EA7;&#x57DF;&#x540D;&#x4E0D;&#x540C;&#xFF0C; document.domain&#x65B9;&#x6CD5;&#xFF1A;&#x83B7;&#x53D6;/&#x8BBE;&#x7F6E;&#x5F53;&#x524D;&#x6587;&#x6863;&#x7684;&#x539F;&#x59CB;&#x57DF;&#x90E8;&#x5206;:</p>
<pre><code class="lang-javascript"><span class="hljs-comment">//&#x521D;&#x59CB;&#x503C; &quot;home.example.com&quot; </span>
<span class="hljs-built_in">document</span>.domain = <span class="hljs-string">&quot;example.com&quot;</span>;         <span class="hljs-comment">//OK</span>
<span class="hljs-built_in">document</span>.domain = <span class="hljs-string">&quot;home.example.com&quot;</span>;     <span class="hljs-comment">//NO,&#x4E0D;&#x80FD;&#x7531;&#x677E;&#x6563;&#x53D8;&#x7D27;&#x7EF7;</span>
<span class="hljs-built_in">document</span>.domain = <span class="hljs-string">&quot;example&quot;</span>;             <span class="hljs-comment">//NO&#xFF0C;&#x5FC5;&#x987B;&#x6709;&#x4E00;&#x4E2A;&#x70B9;&#x53F7;</span>
<span class="hljs-built_in">document</span>.domain = <span class="hljs-string">&quot;another.com&quot;</span>;         <span class="hljs-comment">//NO&#xFF0C; &#x5FC5;&#x987B;&#x662F;&#x6709;&#x6548;&#x57DF;&#x524D;&#x7F00;&#x6216;&#x5176;&#x672C;&#x8EAB;</span>
</code></pre>
<blockquote>
<p>&#x4E00;&#x4E2A;&#x4F8B;&#x5B50;</p>
</blockquote>
<ol>
<li>&#x4FEE;&#x6539;hosts&#x6587;&#x4EF6;&#xFF0C;&#x6A21;&#x62DF;2&#x4E2A;&#x57DF;&#x540D;</li>
</ol>
<pre><code>## sudo vi /etc/hosts 
// &#x5728;&#x6587;&#x4EF6;&#x91CC;&#x6DFB;&#x52A0;&#x5982;&#x4E0B;2&#x884C;&#x5185;&#x5BB9;
127.0.0.1 a.etc.com
127.0.0.1 b.etc.com
</code></pre><ol>
<li><p>&#x521B;&#x5EFA;2&#x4E2A;&#x6587;&#x4EF6;&#xFF0C;&#x7136;&#x540E;&#x542F;&#x52A8;http-server</p>
<p>a.html</p>
<pre><code class="lang-html"><span class="hljs-tag">&lt;<span class="hljs-name">html</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">head</span>&gt;</span>
  <span class="hljs-tag">&lt;<span class="hljs-name">meta</span> <span class="hljs-attr">charset</span>=<span class="hljs-string">&quot;utf-8&quot;</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">style</span>&gt;</span><span class="css">
  <span class="hljs-selector-class">.ct</span>{ <span class="hljs-attribute">width</span>: <span class="hljs-number">910px</span>; <span class="hljs-attribute">margin</span>: auto; }
  <span class="hljs-selector-class">.main</span>{ <span class="hljs-attribute">float</span>: left; <span class="hljs-attribute">width</span>: <span class="hljs-number">450px</span>; <span class="hljs-attribute">height</span>: <span class="hljs-number">300px</span>; <span class="hljs-attribute">border</span>: <span class="hljs-number">1px</span> solid <span class="hljs-number">#ccc</span>;
  }
  <span class="hljs-selector-class">.main</span> <span class="hljs-selector-tag">input</span>{ <span class="hljs-attribute">margin</span>: <span class="hljs-number">20px</span>; <span class="hljs-attribute">width</span>: <span class="hljs-number">200px</span>; }
  <span class="hljs-selector-class">.iframe</span>{ <span class="hljs-attribute">float</span>: right; }
  <span class="hljs-selector-tag">iframe</span>{ <span class="hljs-attribute">width</span>: <span class="hljs-number">450px</span>; <span class="hljs-attribute">height</span>: <span class="hljs-number">300px</span>; <span class="hljs-attribute">border</span>: <span class="hljs-number">1px</span> dashed <span class="hljs-number">#ccc</span>; }
</span><span class="hljs-tag">&lt;/<span class="hljs-name">style</span>&gt;</span>
<span class="hljs-tag">&lt;/<span class="hljs-name">head</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">div</span> <span class="hljs-attr">class</span>=<span class="hljs-string">&quot;ct&quot;</span>&gt;</span>
  <span class="hljs-tag">&lt;<span class="hljs-name">h1</span>&gt;</span>&#x4F7F;&#x7528;&#x964D;&#x57DF;&#x5B9E;&#x73B0;&#x8DE8;&#x57DF;<span class="hljs-tag">&lt;/<span class="hljs-name">h1</span>&gt;</span>
  <span class="hljs-tag">&lt;<span class="hljs-name">div</span> <span class="hljs-attr">class</span>=<span class="hljs-string">&quot;main&quot;</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-name">input</span> <span class="hljs-attr">type</span>=<span class="hljs-string">&quot;text&quot;</span> <span class="hljs-attr">placeholder</span>=<span class="hljs-string">&quot;a.html&quot;</span>&gt;</span>
  <span class="hljs-tag">&lt;/<span class="hljs-name">div</span>&gt;</span>
  <span class="hljs-tag">&lt;<span class="hljs-name">iframe</span> <span class="hljs-attr">src</span>=<span class="hljs-string">&quot;http://b.etc.com:8080/b.html&quot;</span> <span class="hljs-attr">frameborder</span>=<span class="hljs-string">&quot;0&quot;</span> &gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">iframe</span>&gt;</span>
<span class="hljs-tag">&lt;/<span class="hljs-name">div</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">script</span>&gt;</span><span class="javascript">
<span class="hljs-built_in">document</span>.querySelector(<span class="hljs-string">&apos;.main input&apos;</span>).addEventListener(<span class="hljs-string">&apos;input&apos;</span>, <span class="hljs-function"><span class="hljs-keyword">function</span>(<span class="hljs-params"></span>)</span>{
  <span class="hljs-built_in">console</span>.log(<span class="hljs-keyword">this</span>.value);
  <span class="hljs-built_in">window</span>.frames[<span class="hljs-number">0</span>].document.querySelector(<span class="hljs-string">&apos;input&apos;</span>).value = <span class="hljs-keyword">this</span>.value;
})
<span class="hljs-built_in">document</span>.domain = <span class="hljs-string">&quot;etc.com&quot;</span>
</span><span class="hljs-tag">&lt;/<span class="hljs-name">script</span>&gt;</span>
<span class="hljs-tag">&lt;/<span class="hljs-name">html</span>&gt;</span>
</code></pre>
<p>b.html</p>
<pre><code>&lt;html&gt;
&lt;head&gt;
  &lt;meta charset=&quot;utf-8&quot;&gt;
&lt;style&gt;
    html,body{ margin: 0; }
    input{ margin: 20px; width: 200px; }
&lt;/style&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;input id=&quot;input&quot; type=&quot;text&quot;  placeholder=&quot;b.html&quot;&gt;
&lt;script&gt;
document.querySelector(&apos;#input&apos;).addEventListener(&apos;input&apos;, function(){
    window.parent.document.querySelector(&apos;input&apos;).value = this.value;
})
document.domain = &apos;etc.com&apos;;
&lt;/script&gt;
&lt;/body&gt;
&lt;/html&gt;
</code></pre></li>
<li><p>&#x7EC8;&#x7AEF;&#x6253;&#x5F00;&#x8BE5;&#x6587;&#x4EF6;&#x76EE;&#x5F55;&#xFF0C;&#x542F;&#x52A8;&#x670D;&#x52A1;&#xFF1A;</p>
<pre><code>~ http-server

Starting up http-server, serving ./
Available on:
  http://127.0.0.1:8080
  http://192.168.43.183:8080
Hit CTRL-C to stop the server
</code></pre></li>
<li><p>&#x6D4F;&#x89C8;&#x5668;&#x4E2D;&#x6253;&#x5F00;&#x94FE;&#x63A5;&#xFF1A;<code>http://a.etc.com:8080/a.html</code>&#x5C31;&#x80FD;&#x770B;&#x89C1;&#x6548;&#x679C;&#x3002;</p>
<p>&#x5982;&#x679C;&#x4E0D;&#x5728;&#x4E24;&#x4E2A;&#x9875;&#x9762;&#x4E2D;&#x8BBE;&#x7F6E;<code>document.domain = &apos;etc.com&apos;;</code>, &#x90A3;&#x4E48;&#x4E45;&#x6CA1;&#x6709;&#x6548;&#x679C;&#x3002;</p>
</li>
</ol>
<p><a href="https://developer.mozilla.org/zh-CN/docs/Web/API/Document/domain" target="_blank">Document.domain MDN</a></p>
<h3 id="windowpostmessage&#x9875;&#x9762;&#x901A;&#x4FE1;">window.postMessage&#x9875;&#x9762;&#x901A;&#x4FE1;</h3>
<p><code>postMessge()</code>&#x662F;HTML5&#x65B0;&#x5B9A;&#x4E49;&#x7684;&#x901A;&#x4FE1;&#x673A;&#x5236;&#x3002;&#x6240;&#x6709;&#x4E3B;&#x6D41;&#x6D4F;&#x89C8;&#x5668;&#x90FD;&#x5DF2;&#x5B9E;&#x73B0;&#x3002;</p>
<p>postMessage()&#x65B9;&#x6CD5;&#x5141;&#x8BB8;&#x8DE8;&#x7A97;&#x53E3;&#x901A;&#x4FE1;&#xFF0C;&#x4E0D;&#x8BBA;&#x8FD9;&#x4E24;&#x4E2A;&#x7A97;&#x53E3;&#x662F;&#x5426;&#x540C;&#x6E90;&#x3002;</p>
<ul>
<li>&#x53D1;&#x9001;&#x6D88;&#x606F;</li>
</ul>
<pre><code>otherWindow.postMessage(message, targetOrigin);
</code></pre><p><strong>otherWindow</strong>:&#x5176;&#x4ED6;&#x7A97;&#x53E3;&#x7684;&#x4E00;&#x4E2A;&#x5F15;&#x7528;&#xFF0C;&#x6BD4;&#x5982;iframe&#x7684;contentWindow&#x5C5E;&#x6027;&#x3001;&#x6267;&#x884C;<a href="https://developer.mozilla.org/en-US/docs/DOM/window.open" target="_blank">window.open</a>&#x8FD4;&#x56DE;&#x7684;&#x7A97;&#x53E3;&#x5BF9;&#x8C61;&#x3001;&#x6216;&#x8005;&#x662F;&#x547D;&#x540D;&#x8FC7;&#x6216;&#x6570;&#x503C;&#x7D22;&#x5F15;&#x7684;<a href="https://developer.mozilla.org/en-US/docs/DOM/window.frames" target="_blank">window.frames</a>&#x3002;</p>
<p><strong>message</strong>: &#x5C06;&#x8981;&#x53D1;&#x9001;&#x5230;&#x5176;&#x4ED6; window&#x7684;&#x6570;&#x636E;&#x3002;</p>
<p><strong>targetOrigin</strong>:&#x63A5;&#x6536;&#x6D88;&#x606F;&#x7684;&#x7A97;&#x53E3;&#x7684;&#x6E90;&#xFF08;origin&#xFF09;&#xFF0C;&#x5373;&quot;&#x534F;&#x8BAE; + &#x57DF;&#x540D; + &#x7AEF;&#x53E3;&quot;&#x3002;&#x4E5F;&#x53EF;&#x4EE5;&#x8BBE;&#x4E3A;<code>*</code>&#xFF0C;&#x8868;&#x793A;&#x4E0D;&#x9650;&#x5236;&#x57DF;&#x540D;&#xFF0C;&#x5411;&#x6240;&#x6709;&#x7A97;&#x53E3;&#x53D1;&#x9001;&#x3002;</p>
<ul>
<li>&#x76D1;&#x542C;&#x5904;&#x7406;&#x6D88;&#x606F;</li>
</ul>
<p>&#x7236;&#x7A97;&#x53E3;&#x548C;&#x5B50;&#x7A97;&#x53E3;&#x90FD;&#x53EF;&#x4EE5;&#x901A;&#x8FC7;<code>message</code>&#x4E8B;&#x4EF6;&#xFF0C;&#x76D1;&#x542C;&#x5BF9;&#x65B9;&#x7684;&#x6D88;&#x606F;&#x3002;</p>
<pre><code>window.addEventListener(&apos;message&apos;, function(e) {
  console.log(e.data);
});
</code></pre><p><code>message</code>&#x4E8B;&#x4EF6;&#x7684;&#x4E8B;&#x4EF6;&#x5BF9;&#x8C61;<code>event</code>&#xFF0C;&#x63D0;&#x4F9B;&#x4EE5;&#x4E0B;&#x4E09;&#x4E2A;&#x5C5E;&#x6027;&#x3002;</p>
<ul>
<li><code>event.source</code>&#xFF1A;&#x53D1;&#x9001;&#x6D88;&#x606F;&#x7684;&#x7A97;&#x53E3;</li>
<li><code>event.origin</code>: &#x6D88;&#x606F;&#x53D1;&#x5411;&#x7684;&#x7F51;&#x5740;</li>
<li><code>event.data</code>: &#x6D88;&#x606F;&#x5185;&#x5BB9;</li>
</ul>
<p><a href="https://developer.mozilla.org/zh-CN/docs/Web/API/Window/postMessage" target="_blank">window.postMessage mdn</a></p>
<blockquote>
<p>&#x4F8B;&#x5B50;</p>
</blockquote>
<p>&#x4E0A;&#x9762;&#x7684;&#x4EE3;&#x7801;&#x4FEE;&#x6539;&#x4E00;&#x4E0B;&#xFF1A;</p>
<p>a.html</p>
<pre><code class="lang-html"><span class="hljs-tag">&lt;<span class="hljs-name">script</span>&gt;</span><span class="javascript">
  <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">$</span>(<span class="hljs-params">id</span>)</span>{
    <span class="hljs-keyword">return</span> <span class="hljs-built_in">document</span>.querySelector(id);
  }
  $(<span class="hljs-string">&apos;.main input&apos;</span>).addEventListener(<span class="hljs-string">&apos;input&apos;</span>, <span class="hljs-function"><span class="hljs-keyword">function</span>(<span class="hljs-params"></span>)</span>{
    <span class="hljs-built_in">console</span>.log(<span class="hljs-keyword">this</span>.value);
    <span class="hljs-built_in">window</span>.frames[<span class="hljs-number">0</span>].postMessage(<span class="hljs-keyword">this</span>.value,<span class="hljs-string">&apos;*&apos;</span>);
  })
  <span class="hljs-built_in">window</span>.addEventListener(<span class="hljs-string">&apos;message&apos;</span>,<span class="hljs-function"><span class="hljs-keyword">function</span>(<span class="hljs-params">e</span>) </span>{
      $(<span class="hljs-string">&apos;.main input&apos;</span>).value = e.data
      <span class="hljs-built_in">console</span>.log(e.data);
  });
</span><span class="hljs-tag">&lt;/<span class="hljs-name">script</span>&gt;</span>
</code></pre>
<p>b.html</p>
<pre><code class="lang-html"><span class="hljs-tag">&lt;<span class="hljs-name">script</span>&gt;</span><span class="javascript">
    $(<span class="hljs-string">&apos;#input&apos;</span>).addEventListener(<span class="hljs-string">&apos;input&apos;</span>, <span class="hljs-function"><span class="hljs-keyword">function</span>(<span class="hljs-params"></span>)</span>{
        <span class="hljs-built_in">window</span>.parent.postMessage(<span class="hljs-keyword">this</span>.value, <span class="hljs-string">&apos;*&apos;</span>);
    })
    <span class="hljs-built_in">window</span>.addEventListener(<span class="hljs-string">&apos;message&apos;</span>,<span class="hljs-function"><span class="hljs-keyword">function</span>(<span class="hljs-params">e</span>) </span>{
        $(<span class="hljs-string">&apos;#input&apos;</span>).value = e.data
        <span class="hljs-built_in">console</span>.log(e);
    });
    <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">$</span>(<span class="hljs-params">id</span>)</span>{
        <span class="hljs-keyword">return</span> <span class="hljs-built_in">document</span>.querySelector(id);
    }
</span><span class="hljs-tag">&lt;/<span class="hljs-name">script</span>&gt;</span>
</code></pre>
<h2 id="&#x53C2;&#x8003;&#x8D44;&#x6599;">&#x53C2;&#x8003;&#x8D44;&#x6599;</h2>
<p><a href="http://book.jirengu.com/fe/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/Javascript/%E8%B7%A8%E5%9F%9F.html" target="_blank">&#x9965;&#x4EBA;&#x8C37;&#x8DE8;&#x57DF;&#x8BFE;&#x4EF6;</a></p>
<p><a href="http://www.ruanyifeng.com/blog/2016/04/cors.html" target="_blank">&#x8DE8;&#x57DF;&#x8D44;&#x6E90;&#x5171;&#x4EAB; CORS &#x8BE6;&#x89E3; &#x962E;&#x4E00;&#x5CF0;</a></p>
<p><a href="http://www.ruanyifeng.com/blog/2016/04/same-origin-policy.html" target="_blank">&#x6D4F;&#x89C8;&#x5668;&#x540C;&#x6E90;&#x653F;&#x7B56;&#x53CA;&#x5176;&#x89C4;&#x907F;&#x65B9;&#x6CD5; &#x962E;&#x4E00;&#x5CF0;</a></p>
<p><a href="https://segmentfault.com/a/1190000006908944" target="_blank">&#x5173;&#x4E8E;&#x8DE8;&#x57DF; SegmentFault</a></p>

                                
                                </section>
                            
    </div>
    <div class="search-results">
        <div class="has-results">
            
            <h1 class="search-results-title"><span class='search-results-count'></span> results matching "<span class='search-query'></span>"</h1>
            <ul class="search-results-list"></ul>
            
        </div>
        <div class="no-results">
            
            <h1 class="search-results-title">No results matching "<span class='search-query'></span>"</h1>
            
        </div>
    </div>
</div>

                        </div>
                    </div>
                
            </div>

            
                
                <a href="JS-4数据类型转换.html" class="navigation navigation-prev " aria-label="Previous page: 4数据类型转换">
                    <i class="fa fa-angle-left"></i>
                </a>
                
                
                <a href="6Ajax.md" class="navigation navigation-next " aria-label="Next page: 6Ajax">
                    <i class="fa fa-angle-right"></i>
                </a>
                
            
        
    </div>

    <script>
        var gitbook = gitbook || [];
        gitbook.push(function() {
            gitbook.page.hasChanged({"page":{"title":"5跨域","level":"1.4.9","depth":2,"next":{"title":"6Ajax","level":"1.4.10","depth":2,"path":"doc/JavaScript/6Ajax.md","ref":"doc/JavaScript/6Ajax.md","articles":[]},"previous":{"title":"4数据类型转换","level":"1.4.8","depth":2,"path":"doc/JavaScript/JS-4数据类型转换.md","ref":"doc/JavaScript/JS-4数据类型转换.md","articles":[]},"dir":"ltr"},"config":{"gitbook":"*","theme":"default","variables":{},"plugins":["livereload"],"pluginsConfig":{"livereload":{},"highlight":{},"search":{},"lunr":{"maxIndexSize":1000000,"ignoreSpecialCharacters":false},"sharing":{"facebook":true,"twitter":true,"google":false,"weibo":false,"instapaper":false,"vk":false,"all":["facebook","google","twitter","weibo","instapaper"]},"fontsettings":{"theme":"white","family":"sans","size":2},"theme-default":{"styles":{"website":"styles/website.css","pdf":"styles/pdf.css","epub":"styles/epub.css","mobi":"styles/mobi.css","ebook":"styles/ebook.css","print":"styles/print.css"},"showLevel":false}},"structure":{"langs":"LANGS.md","readme":"README.md","glossary":"GLOSSARY.md","summary":"SUMMARY.md"},"pdf":{"pageNumbers":true,"fontSize":12,"fontFamily":"Arial","paperSize":"a4","chapterMark":"pagebreak","pageBreaksBefore":"/","margin":{"right":62,"left":62,"top":56,"bottom":56}},"styles":{"website":"styles/website.css","pdf":"styles/pdf.css","epub":"styles/epub.css","mobi":"styles/mobi.css","ebook":"styles/ebook.css","print":"styles/print.css"}},"file":{"path":"doc/JavaScript/JS-5跨域.md","mtime":"2018-05-14T02:44:07.979Z","type":"markdown"},"gitbook":{"version":"3.2.3","time":"2018-10-30T03:47:33.035Z"},"basePath":"../..","book":{"language":""}});
        });
    </script>
</div>

        
    <script src="../../gitbook/gitbook.js"></script>
    <script src="../../gitbook/theme.js"></script>
    
        
        <script src="../../gitbook/gitbook-plugin-livereload/plugin.js"></script>
        
    
        
        <script src="../../gitbook/gitbook-plugin-search/search-engine.js"></script>
        
    
        
        <script src="../../gitbook/gitbook-plugin-search/search.js"></script>
        
    
        
        <script src="../../gitbook/gitbook-plugin-lunr/lunr.min.js"></script>
        
    
        
        <script src="../../gitbook/gitbook-plugin-lunr/search-lunr.js"></script>
        
    
        
        <script src="../../gitbook/gitbook-plugin-sharing/buttons.js"></script>
        
    
        
        <script src="../../gitbook/gitbook-plugin-fontsettings/fontsettings.js"></script>
        
    

    </body>
</html>

